### ISSUE TITLE
FlowForge Dashboard – Preparation phase

### ISSUE THREAD

**Issue by MarianRaphael** [flowforge/flowforge-nr-dashboard#26]
### Description

- [x] Set Up Repo Structure
- [x] Decide on a Framework: Vue vs. React
- [x] Evaluate Backward Compatibility Options
- [x] Specify Freelancer Requirements
- [x] Begin with First Iteration of Development
